# Generated by Django 2.2.9 on 2020-06-07 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='ФИО')),
                ('role', models.IntegerField(blank=True, choices=[(1, 'Администратор'), (2, 'Автор интервенции'), (3, 'Исследователь')], default=1, null=True, verbose_name='Роль')),
            ],
        ),
        migrations.CreateModel(
            name='EducatInst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Образовательное учреждение')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('annotation', models.TextField(verbose_name='Описание')),
                ('subject', models.CharField(choices=[('M', 'Математика'), ('I', 'Информатика'), ('R', 'Русский язык'), ('L', 'Литература'), ('F', 'Иностранный язык')], default='MATHS', max_length=2, verbose_name='Дисциплина')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntervParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('type', models.IntegerField(choices=[(1, 'NUMBER'), (2, 'TEXT'), (3, 'FILE'), (4, 'IMAGE')], default=1, verbose_name='Тип параметра')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_parameters', to='project.Intervention', verbose_name='Интервенция параметра')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('effect', models.FloatField(default=0, verbose_name='Эффективность интервенции по исследованию')),
                ('status', models.CharField(blank=True, choices=[('in work', 'В работе'), ('completed', 'Завершено'), ('canceled', 'Отменено')], default='in work', max_length=50, null=True, verbose_name='Статус')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_interv', to='project.Intervention', verbose_name='Исследование интервенции')),
                ('organization', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_research', to='project.EducatInst')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='StageResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер этапа')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.TextField(blank=True, null=True)),
                ('protocol', models.FileField(default='file', upload_to='')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_template', to='project.Intervention', verbose_name='Шаблон исследования')),
            ],
        ),
        migrations.CreateModel(
            name='TemplParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=70)),
                ('type', models.IntegerField(choices=[(1, 'NUMBER'), (2, 'TEXT'), (3, 'FILE'), (4, 'IMAGE')], default=1, verbose_name='Тип параметра')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_param', to='project.Template', verbose_name='Параметр исследования')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер задачи')),
                ('name', models.CharField(max_length=255)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_stage', to='project.StageResearch', verbose_name='Этап задачи')),
            ],
        ),
        migrations.AddField(
            model_name='stageresearch',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_research', to='project.Template', verbose_name='Этап исследования'),
        ),
        migrations.CreateModel(
            name='ResponsTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('in work', 'В работе'), ('completed', 'Завершено'), ('canceled', 'Отменено')], default='in work', max_length=50, null=True, verbose_name='Статус')),
                ('report', models.FileField(null=True, upload_to='')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_stage', to='project.Research', verbose_name='Исследование')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.CustomUser')),
                ('taskstage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_stage', to='project.TaskStage', verbose_name='Этап задачи')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchParamValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, default=0, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='')),
                ('image', models.ImageField(upload_to='')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templ_param', to='project.TemplParam')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research', to='project.Research')),
            ],
        ),
        migrations.AddField(
            model_name='research',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='project.Template'),
        ),
        migrations.CreateModel(
            name='ParamValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, default=0, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='')),
                ('image', models.ImageField(upload_to='')),
                ('param', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='param_values', to='project.IntervParam', verbose_name='Значение параметра')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.EducatInst', verbose_name='Образовательное учреждение'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
