# Generated by Django 2.2.9 on 2020-01-05 11:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poзst',
            new_name='Post',
        ),
    ]
