# Generated by Django 2.2.9 on 2020-01-07 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200107_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='sphere',
            field=models.CharField(choices=[('M', 'Математика'), ('R', 'Русский язык'), ('L', 'Литература')], default='MATHS', max_length=2, verbose_name='Тематическая область'),
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('type', models.IntegerField(choices=[(1, 'NUMBER'), (2, 'TEXT'), (3, 'FILE'), (4, 'PHOTO'), (5, 'LIST'), (6, 'LINK')], default=1, verbose_name='Тип параметра')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_parameters', to='project.Intervention', verbose_name='Ссылка на интервенцию')),
            ],
        ),
    ]
