# Generated by Django 2.2.9 on 2020-01-26 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200107_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='param',
            name='type',
            field=models.IntegerField(choices=[(1, 'NUMBER'), (2, 'TEXT'), (3, 'FILE'), (4, 'IMAGE')], default=1, verbose_name='Тип параметра'),
        ),
        migrations.CreateModel(
            name='ParamValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, default=0, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_values', to='project.Param', verbose_name='Значение параметра')),
            ],
        ),
    ]
