# Generated by Django 2.2.9 on 2020-01-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200126_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramvalue',
            name='value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
