# Generated by Django 2.2.9 on 2020-01-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20200126_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramvalue',
            name='value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
