# Generated by Django 2.2.9 on 2020-02-08 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20200126_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('file', models.FileField(upload_to='')),
                ('param_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project.ParamValue')),
            ],
        ),
    ]
