# Generated by Django 2.2.9 on 2020-02-08 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_uploaddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddata',
            name='param_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project.Param'),
        ),
    ]
