# Generated by Django 2.2.9 on 2020-02-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20200208_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramvalue',
            name='file',
            field=models.FileField(default='test', upload_to=''),
        ),
        migrations.AddField(
            model_name='paramvalue',
            name='image',
            field=models.ImageField(default='image', upload_to=''),
        ),
        migrations.DeleteModel(
            name='UploadData',
        ),
    ]
