# Generated by Django 2.2.9 on 2020-02-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20200208_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramvalue',
            name='file',
            field=models.FileField(upload_to='C:/Users/Zar/Desktop/Файлы'),
        ),
    ]
