# Generated by Django 2.2.9 on 2020-02-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20200209_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paramvalue',
            name='image',
        ),
        migrations.AlterField(
            model_name='paramvalue',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
