# Generated by Django 2.2.9 on 2020-02-09 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20200209_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paramvalue',
            name='file',
        ),
        migrations.CreateModel(
            name='UploadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_for_file', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('file', models.FileField(upload_to='')),
                ('sub_param_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project.ParamValue')),
            ],
        ),
    ]
