# Generated by Django 2.2.9 on 2020-02-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20200209_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaddata',
            name='header_for_file',
        ),
    ]
