# Generated by Django 2.2.9 on 2020-02-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_remove_uploaddata_header_for_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramvalue',
            name='file',
            field=models.FileField(default='file', upload_to=''),
        ),
    ]
