# Generated by Django 2.2.9 on 2020-02-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_paramvalue_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paramvalue',
            name='file',
        ),
    ]
