# Generated by Django 2.2.9 on 2020-02-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_remove_paramvalue_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramvalue',
            name='file',
            field=models.FileField(default='file', upload_to=''),
        ),
    ]
