# Generated by Django 2.2.9 on 2020-02-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_paramvalue_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramvalue',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='UploadData',
        ),
    ]
