# Generated by Django 2.2.9 on 2020-02-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_remove_paramvalue_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramvalue',
            name='image',
            field=models.ImageField(default='image', upload_to=''),
        ),
    ]
