# Generated by Django 2.2.9 on 2020-02-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_paramvalue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='annotation',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
