# Generated by Django 2.2.9 on 2020-02-14 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20200212_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('value', models.FloatField(blank=True, default=0, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(default='file', upload_to='')),
                ('image', models.ImageField(default='image', upload_to='')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_template', to='project.Intervention', verbose_name='Шаблон исследования')),
            ],
        ),
        migrations.CreateModel(
            name='TemplParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'NUMBER'), (2, 'TEXT'), (3, 'FILE'), (4, 'IMAGE')], default=1, verbose_name='Тип параметра')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='project.Template', verbose_name='Параметр исследования')),
            ],
        ),
    ]
