# Generated by Django 2.2.9 on 2020-02-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_template_templparam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='file',
        ),
        migrations.RemoveField(
            model_name='template',
            name='image',
        ),
        migrations.RemoveField(
            model_name='template',
            name='text',
        ),
        migrations.RemoveField(
            model_name='template',
            name='value',
        ),
        migrations.AddField(
            model_name='templparam',
            name='file',
            field=models.FileField(default='file', upload_to=''),
        ),
        migrations.AddField(
            model_name='templparam',
            name='image',
            field=models.ImageField(default='image', upload_to=''),
        ),
        migrations.AddField(
            model_name='templparam',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templparam',
            name='value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
