# Generated by Django 2.2.9 on 2020-02-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_auto_20200214_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='templparam',
            name='name',
            field=models.CharField(default='test', max_length=70),
        ),
    ]
