# Generated by Django 2.2.9 on 2020-03-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_templparam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='formula',
            field=models.TextField(blank=True, null=True),
        ),
    ]
