# Generated by Django 2.2.9 on 2020-03-09 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_template_formula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='project.Template')),
            ],
        ),
        migrations.RemoveField(
            model_name='templparam',
            name='file',
        ),
        migrations.RemoveField(
            model_name='templparam',
            name='image',
        ),
        migrations.RemoveField(
            model_name='templparam',
            name='text',
        ),
        migrations.RemoveField(
            model_name='templparam',
            name='value',
        ),
        migrations.AlterField(
            model_name='templparam',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_param', to='project.Template', verbose_name='Параметр исследования'),
        ),
        migrations.CreateModel(
            name='ResearchParamValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, default=0, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(default='file', upload_to='')),
                ('image', models.ImageField(default='image', upload_to='')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templ_param', to='project.TemplParam')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research', to='project.Research')),
            ],
        ),
    ]
