# Generated by Django 2.2.9 on 2020-03-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_research_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='effect',
            field=models.IntegerField(default=0, verbose_name='Эффективность интервенции по исследованию'),
        ),
    ]
