# Generated by Django 2.2.9 on 2020-04-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='sphere',
            field=models.CharField(choices=[('M', 'Математика'), ('R', 'Русский язык'), ('L', 'Литература')], default='MATHS', max_length=2, verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='paramvalue',
            name='value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
