# Generated by Django 2.2.9 on 2020-04-22 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_auto_20200418_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=None, verbose_name='Номер этапа')),
                ('name', models.CharField(default='null', max_length=255)),
                ('template', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stage_research', to='project.Template', verbose_name='Этап исследования')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=None, verbose_name='Номер этапа')),
                ('name', models.CharField(default='null', max_length=255)),
                ('stage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='task_stage', to='project.StageResearch', verbose_name='Этап задачи')),
            ],
        ),
    ]
