# Generated by Django 2.2.9 on 2020-04-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_stageresearch_taskstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.CharField(default='', max_length=255, verbose_name='организация'),
        ),
        migrations.AlterField(
            model_name='taskstage',
            name='number',
            field=models.IntegerField(default=None, verbose_name='Номер задачи'),
        ),
    ]
