# Generated by Django 2.2.9 on 2020-04-26 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_auto_20200426_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducatInst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='образовательное учреждение')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.EducatInst'),
        ),
    ]
