# Generated by Django 2.2.9 on 2020-04-27 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_auto_20200426_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_research', to='project.EducatInst'),
        ),
    ]
