# Generated by Django 2.2.9 on 2020-04-28 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_research_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='name',
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.CustomUser')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.StageResearch')),
            ],
        ),
    ]
