# Generated by Django 2.2.9 on 2020-05-05 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_research_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='responsible',
        ),
        migrations.AddField(
            model_name='taskstage',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.CustomUser'),
        ),
    ]
