# Generated by Django 2.2.9 on 2020-05-05 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_auto_20200505_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstage',
            name='responsible',
        ),
        migrations.CreateModel(
            name='ResponsResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='task_stage', to='project.Research', verbose_name='Исследование')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.CustomUser')),
                ('taskstage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='task_stage', to='project.TaskStage', verbose_name='Этап задачи')),
            ],
        ),
    ]
