# Generated by Django 2.2.9 on 2020-05-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_auto_20200505_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='status',
            field=models.CharField(blank=True, choices=[('in work', 'В работе'), ('completed', 'Завершено'), ('canceled', 'Отменено')], default='in work', max_length=50, null=True, verbose_name='Статус'),
        ),
    ]
