# Generated by Django 2.2.9 on 2020-05-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_research_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='published_date',
        ),
        migrations.AddField(
            model_name='template',
            name='protocol',
            field=models.FileField(default='file', upload_to=''),
        ),
    ]
