# Generated by Django 2.2.9 on 2020-05-11 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0043_auto_20200508_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.CustomUser'),
        ),
    ]
