# Generated by Django 2.2.9 on 2020-05-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0044_research_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='description',
        ),
    ]
