# Generated by Django 2.2.9 on 2020-05-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_remove_template_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='effect',
            field=models.FloatField(default=0, verbose_name='Эффективность интервенции по исследованию'),
        ),
    ]
