# Generated by Django 2.2.9 on 2020-05-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_auto_20200512_1325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResponsResearch',
            new_name='ResponsTask',
        ),
    ]
