# Generated by Django 2.2.9 on 2020-05-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0047_auto_20200512_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='responstask',
            name='report',
            field=models.FileField(default='report', upload_to=''),
        ),
        migrations.AddField(
            model_name='responstask',
            name='status',
            field=models.CharField(blank=True, choices=[('in work', 'В работе'), ('completed', 'Завершено'), ('canceled', 'Отменено')], default='in work', max_length=50, null=True, verbose_name='Статус'),
        ),
    ]
