# Generated by Django 2.2.9 on 2020-05-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0048_auto_20200512_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responstask',
            name='report',
            field=models.FileField(upload_to=''),
        ),
    ]
